In [1]:
import pandas as pd
import numpy as np

In [2]:
cd the_great_merge/check_these

/Users/anthea.mitchell/Desktop/Coding/CSVs/the_great_merge/check_these

In [3]:
Main_List=pd.read_csv('CT_Vaccination_status.csv')
new_csv = pd.read_csv('AllAspen_PangoResults_Aug30-2021.csv')
Main_List

     Sample_ID     E gene     N gene  RNase P gene Vaccinated?  Note:
0    BXRSCDULQ  13.248019  13.009094     26.720560          no    NaN
1    BXEPC7PS1  13.803771  14.059277     21.886399         yes    NaN
2    BXCV5D4SW  13.894834  13.065624     27.138541         yes    NaN
3    BXLBJT1NJ  14.199987  14.302166     28.584464          no    NaN
4    BX1QL85JC  14.561974  15.463401     29.519649         yes    NaN
..         ...        ...        ...           ...         ...    ...
316  BXK6D41AT  28.018962  23.501013     26.614399          no    NaN
317  BXQ2AVRAR  28.270004  29.094068     29.552605          no    NaN
318  BXDNBJ6DB  31.513418  36.158955     31.925891         unk    NaN
319  BX76G6359  31.962000  32.441880     34.161122         yes    NaN
320  BXU6SBH94  21.533181  23.441585     28.937142         yes    NaN

[321 rows x 6 columns]

In [4]:
new_csv.replace('', np.NaN)

,Sequence,Lineage,Conflict,Ambiguity_score,Scorpio_call,Scorpio_support,Scorpio conflict,Note,pangolin version,pangoLEARN version
0,BXCJ95D9Q,B.1.617.2,0,0.999404,Delta (B.1.617.2-like),0.9231,0,scorpio call: Alt alleles 12; Ref alleles 0; A...,v3.1.11,8/9/21
1,BXCVHAVJL,AY.12,0,0.999926,Delta (B.1.617.2-like),0.9231,0,scorpio call: Alt alleles 12; Ref alleles 0; A...,v3.1.11,8/9/21
2,BXG7AE5LK,AY.4,0,0.987178,Delta (B.1.617.2-like),0.9231,0,scorpio call: Alt alleles 12; Ref alleles 0; A...,v3.1.11,8/9/21
3,BXK47JFFF,B.1.617.2,0,0.999926,Delta (B.1.617.2-like),0.9231,0,scorpio call: Alt alleles 12; Ref alleles 0; A...,v3.1.11,8/9/21
4,BXTEVT5L6,B.1.617.2,0,0.999888,Delta (B.1.617.2-like),0.9231,0,scorpio call: Alt alleles 12; Ref alleles 0; A...,v3.1.11,8/9/21
...,...,...,...,...,...,...,...,...,...,...
279,BX8GFAFVG,B.1.617.2,0,0.954897,Delta (B.1.617.2-like),1.0000,0,scorpio call: Alt alleles 13; Ref alleles 0; A...,v3.1.11,8/9/21
280,BX4J223SQ,AY.12,0,0.996825,Delta (B.1.617.2-like),1.0000,0,scorpio call: Alt alleles 13; Ref alleles 0; A...,v3.1.11,8/9/21
281,BXR47VRDE,B.1.617.2,0,0.996862,Delta (B.1.617.2-like),1.0000,0,scorpio call: Alt alleles 13; Ref alleles 0; A...,v3.1.11,8/9/21
282,BX6LC5PM3,B.1.617.2,0,0.996150,Delta (B.1.617.2-like),1.0000,0,scorpio call: Alt alleles 13; Ref alleles 0; A...,v3.1.11,8/9/21
283,BXVAWCCD8,B.1.617.2,0,0.996862,Delta (B.1.617.2-like),1.0000,0,scorpio call: Alt alleles 13; Ref alleles 0; A...,v3.1.11,8/9/21

In [5]:
Main_List = Main_List.drop_duplicates(subset=None, keep='first', inplace=False)
Main_List
New_doc = pd.merge(Main_List, new_csv, left_on=['Sample_ID'], 
             right_on= ['Sequence'], how='left')
New_doc.to_csv('MERGE.csv')